### ISSUE TITLE
It'd be great to support compressing via an io.Writer

### ISSUE THREAD

**Issue by paultag** [xi2/xz#4]
It'd be awesome if in addition to reading xz files (works awesomely, thanks a ton for your work), that it'd be able to write out .xz files.

**Comment by xi2** [comment]
Thank you for your kind words, Paul. It is appreciated.

I notice you are connected with Debian. My motivation for creating the decompressor was actually to unpack deb package files on my own system, so it's kind of cool if you are using it for that!

The reason a compressor does not yet exist is that this package is a port of the C decompression code from the Linux kernel, with the missing features added so that it reads all XZ files. The kernel does not have a compressor so I didn't port it, and porting the C code from XZ utils looked like too much work at the time. I agree that having a compressor would be nice, so I might revisit that decision at some point. I will also leave this bug open to remind me.

However, more likely than that is the package at <https://github.com/ulikunitz/xz> will get finished soon. This is a compressor and decompressor being written from scratch by someone much smarter than me. When it is done my package will probably become redundant. However until then it is useful :)

Best wishes

**Comment by paultag** [comment]
@xi2 That's awesome! I'm using it for the same in [go-debian's deb unpacker](http://godoc.org/pault.ag/go/debian/deb), which is going to be built up to be some really nice primitives. I was stunned to see such a great implementation, it was hugely helpful, and worked like a dream!

Ah, I see. That makes total sense. I have to imagine just getting the decoder was a task, and it looked complex enough where I didn't trust myself at all :)

Thanks for the link, I'll check into that, but thanks for all your work! I'll likely still use this until writing is on the critical path anyway :)

**Comment by xi2** [comment]
Hi again. Your Debian Toolbelt for Go looks like a great idea. I just thought I'd add finally that this package is already in Debian if you do wind up using it longer term. See <https://packages.debian.org/sid/golang-xi2-x-xz-dev>. Sorry if you knew that already!

**Comment by tianon** [comment]
Can confirm, rocking amounts of simple: https://github.com/tianon/go-aptsources/commit/68ee2c4fc308abecafa2f12b73cdd38eace695d6

:metal: :heart:

@paultag wants to do hairy and interesting things with on-the-fly `xz` creation too, so I'll also be watching this space :heart:

**Comment by xi2** [comment]
I'm closing this issue, just because I have no current plans to support compression, and `https://github.com/ulikunitz/xz` seems to support this now. I have also linked to that package in `README.md`.
